# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrxHbvqhG7ktpjbzTdq-ljSkwk8w7c40
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.integrate import quad, solve_ivp
from scipy.interpolate import interp1d

# ==========================================
# SCRIPT FOR FIGURE 1: MASS-RADIUS RELATION
# ==========================================

# --- 1. CONSTANTS & UNITS ---
HBAR_C = 197.327          # MeV fm
MN = 939.565              # Neutron Mass (MeV)
HC_FACTOR = 1.0/(HBAR_C**3)
MEV_FM3_TO_KM2 = 1.3234e-6 # Geometric Units Conversion
KM_TO_MSUN = 1.0/1.4766    # Mass Conversion

# --- 2. MODEL PARAMETERS (FINAL CALIBRATION) ---
ALPHA_FINAL = 4.1          # The Golden Parameter
K_CUTOFF = 250.0           # Cutoff scale in MeV

# --- 3. PHYSICS KERNEL ---
def phi_suppression(k, alpha, k_cut):
    """Geometric Phase Space Suppression Kernel"""
    return 1.0 / (1.0 + alpha * (k/k_cut)**2)

def integrand_energy(k, alpha, k_cut):
    E = np.sqrt(k**2 + MN**2)
    return (1.0/np.pi**2) * phi_suppression(k, alpha, k_cut) * k**2 * E

def integrand_pressure(k, alpha, k_cut):
    E = np.sqrt(k**2 + MN**2)
    return (1.0/(3*np.pi**2)) * phi_suppression(k, alpha, k_cut) * (k**4)/E

# --- 4. SOLVER ENGINE ---
def generate_model():
    print(f"Generating EoS for Alpha={ALPHA_FINAL}...")

    # A. Generate Equation of State
    k_vals = np.linspace(10, 3000, 400) # High resolution
    rho_list, p_list = [], []

    for kf in k_vals:
        e_raw, _ = quad(integrand_energy, 0, kf, args=(ALPHA_FINAL, K_CUTOFF))
        p_raw, _ = quad(integrand_pressure, 0, kf, args=(ALPHA_FINAL, K_CUTOFF))

        # Convert to Geometric Units
        rho_geo = e_raw * HC_FACTOR * MEV_FM3_TO_KM2
        p_geo   = p_raw * HC_FACTOR * MEV_FM3_TO_KM2

        rho_list.append(rho_geo)
        p_list.append(p_geo)

    eos_rho = np.array(rho_list)
    eos_p = np.array(p_list)

    # Export EoS to CSV (Optional but good for repo)
    df_eos = pd.DataFrame({'pressure_geom': eos_p, 'density_geom': eos_rho})
    df_eos.to_csv('eos_data_fig1.csv', index=False)

    # B. Solve TOV
    print("Solving TOV Equations...")
    p_to_rho = interp1d(eos_p, eos_rho, kind='cubic', fill_value="extrapolate")

    def tov(r, y):
        P, m = y
        if P <= 0: return [0, 0]
        rho = p_to_rho(P)
        denom = r*(r-2*m) if r > 1e-4 else 1.0
        dP = - (rho+P)*(m + 4*np.pi*r**3*P) / denom
        dm = 4*np.pi*r**2*rho
        return [dP, dm]

    def surface(r, y): return y[0]
    surface.terminal = True
    surface.direction = -1

    # Sweep Central Pressures
    central_ps = np.logspace(np.log10(eos_p[20]), np.log10(eos_p[-10]), 100)
    masses, radii = [], []

    for Pc in central_ps:
        r_min, rho_c = 1e-4, p_to_rho(Pc)
        m_min = 4/3*np.pi*r_min**3 * rho_c

        sol = solve_ivp(tov, [r_min, 30], [Pc, m_min], events=surface, rtol=1e-6)

        if sol.status == 1:
            M = sol.y[1][-1] * KM_TO_MSUN
            R = sol.t[-1]
            if M > 0.5: # Filter artifacts
                masses.append(M)
                radii.append(R)

    return np.array(radii), np.array(masses)

# --- 5. EXECUTION & PLOTTING ---
R, M = generate_model()
max_mass = np.max(M)
max_idx = np.argmax(M)
R_at_max = R[max_idx]

print(f"\nRESULTS FIG 1:\nMax Mass: {max_mass:.3f} Mo\nRadius at Max: {R_at_max:.2f} km")

# Plotting Figure 1
plt.style.use('default')
fig, ax = plt.subplots(figsize=(7, 6))

# Plot Curve
ax.plot(R, M, color='#D32F2F', linewidth=2.5, label=f'Geometric Model ($\\alpha={ALPHA_FINAL}$)')

# Constraints
ax.axhline(2.35, color='#FBC02D', linestyle='--', linewidth=1.5, label='PSR J0952-0607 ($2.35 M_{\\odot}$)')
ax.axvspan(11.4, 13.0, color='gray', alpha=0.15, label='NICER/LIGO Constraints')
ax.axhspan(2.0, 2.35, color='#FBC02D', alpha=0.05) # Uncertainty band

# Annotations
ax.scatter(R_at_max, max_mass, color='black', zorder=5)
ax.text(R_at_max + 0.5, max_mass, f'Max: {max_mass:.2f} $M_{{\\odot}}$', va='center')

# Labels and Limits
ax.set_xlabel('Radius (km)', fontsize=12)
ax.set_ylabel('Mass ($M_{\\odot}$)', fontsize=12)
ax.set_title('Mass-Radius Relation with Phase Space Suppression', fontsize=14, pad=15)
ax.legend(loc='lower left', frameon=True, fontsize=10)
ax.grid(True, linestyle=':', alpha=0.6)
ax.set_xlim(10, 18) # Adjusted to show the full curve
ax.set_ylim(0.5, 2.8)

plt.tight_layout()
plt.savefig('figure1_mr_relation.pdf', dpi=300)
print("Figure 1 saved successfully as 'figure1_mr_relation.pdf'")